import type { BlogPost, StoreFAQ, Testimonial } from "@/types";

export const blogPosts: BlogPost[] = [
  {
    slug: "choosing-the-right-coffee-for-your-routine",
    title: "Choosing the Right Coffee for Your Routine",
    excerpt: "Black, 3-in-1, or white coffee? A simple guide to picking the cup that fits your taste and your day.",
    category: "Coffee Guides",
    author: "Rhea Bautista",
    publishedAt: "2026-09-18T09:00:00+08:00",
    readingMinutes: 4,
    tone: "coffee",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=75",
    relatedProductSlugs: ["lingzhi-black-coffee", "lingzhi-coffee-3-in-1", "white-coffee-zhino"],
    content: [
      { type: "p", text: "Choosing a coffee is mostly about taste and convenience. Here's a quick way to think about the options we carry." },
      { type: "h2", text: "If you like it simple and bold" },
      { type: "p", text: "Black coffee has no creamer or sugar. It's the most flexible option because you control what you add. Customers who drink their coffee plain or with just a bit of sugar tend to prefer it." },
      { type: "h2", text: "If you want it ready to drink" },
      { type: "p", text: "3-in-1 coffee already includes creamer and sugar. Just add hot water and stir. It's creamy, a bit sweet, and very convenient for the office or busy mornings." },
      { type: "h2", text: "If you like a milky café-style cup" },
      { type: "p", text: "White coffee is milder and creamier than a typical 3-in-1. It's a good match if you usually order lattes." },
      { type: "list", items: ["Plain or lightly sweet: Black Coffee", "Creamy and convenient: 3-in-1", "Milky and mellow: White Coffee"] },
      { type: "note", text: "Still unsure? Ask our AI assistant to compare options based on how you like your coffee." },
    ],
  },
  {
    slug: "how-to-store-your-coffee-products-properly",
    title: "How to Store Your Coffee Products Properly",
    excerpt: "Humidity is the enemy of instant coffee. Keep your sachets fresh with these practical tips.",
    category: "Tips",
    author: "Rhea Bautista",
    publishedAt: "2026-09-08T09:00:00+08:00",
    readingMinutes: 3,
    tone: "cream",
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=75",
    relatedProductSlugs: ["lingzhi-coffee-3-in-1", "cocozhi-cocoa-drink"],
    content: [
      { type: "p", text: "Philippine weather can be humid, and instant coffee absorbs moisture easily. A few habits help keep every cup tasting right." },
      { type: "h2", text: "Keep boxes sealed and off the counter" },
      { type: "p", text: "Store boxes in a cool, dry cabinet away from the stove and direct sunlight. Heat and steam can cause clumping." },
      { type: "h2", text: "Use opened sachets right away" },
      { type: "p", text: "Once a sachet is opened, use it immediately. Don't fold and save half a sachet for later." },
      { type: "list", items: ["Cool, dry cabinet", "Away from sunlight and the stove", "Check the best-before date on the box", "Use opened sachets immediately"] },
    ],
  },
  {
    slug: "understanding-product-labels-and-ingredients",
    title: "Understanding Product Labels and Ingredients",
    excerpt: "What to look for on a label: net content, ingredients order, storage, and registration details.",
    category: "Product Education",
    author: "Rhea Bautista",
    publishedAt: "2026-08-27T09:00:00+08:00",
    readingMinutes: 5,
    tone: "sage",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=75",
    relatedProductSlugs: ["spirulina-tablets", "rg-reishi-gano"],
    content: [
      { type: "p", text: "Reading labels helps you compare products and make informed choices. Here's what each part tells you." },
      { type: "h2", text: "Ingredients are listed by amount" },
      { type: "p", text: "Ingredients usually appear from largest to smallest amount. If sugar is listed first or second, the product is likely on the sweeter side." },
      { type: "h2", text: "Food supplements are not medicines" },
      { type: "p", text: "In the Philippines, food supplements carry a reminder that they are not medicines and have no approved therapeutic claims. If you have a health condition or take medication, talk to your doctor before trying any supplement." },
      { type: "h2", text: "Check storage and dates" },
      { type: "p", text: "Follow storage instructions and check best-before or expiry dates, especially for products you buy in bulk." },
      { type: "note", text: "Our AI assistant only shares information from approved product labels, and it will always suggest consulting a healthcare professional for medical questions." },
    ],
  },
  {
    slug: "easy-iced-coffee-at-home",
    title: "Easy Iced Coffee at Home",
    excerpt: "Three simple ways to turn your favorite sachet into a refreshing iced drink.",
    category: "Recipes",
    author: "Rhea Bautista",
    publishedAt: "2026-08-12T09:00:00+08:00",
    readingMinutes: 3,
    tone: "clay",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=75",
    relatedProductSlugs: ["lingzhi-coffee-3-in-1", "white-coffee-zhino", "cocozhi-cocoa-drink"],
    content: [
      { type: "p", text: "Hot afternoon? Instant coffee works great over ice if you dissolve it properly first." },
      { type: "h2", text: "The basic method" },
      { type: "list", items: ["Dissolve 1 sachet in 50 ml hot water", "Fill a glass with ice", "Pour the coffee over the ice", "Top with cold water or milk"] },
      { type: "h2", text: "Try a mocha" },
      { type: "p", text: "Mix half a sachet of Cocozhi with a 3-in-1 sachet for a simple iced mocha." },
    ],
  },
  {
    slug: "how-ordering-works",
    title: "How Ordering Works with an Independent Seller",
    excerpt: "From inquiry to delivery: what happens after you send an order inquiry.",
    category: "Ordering",
    author: "Rhea Bautista",
    publishedAt: "2026-07-30T09:00:00+08:00",
    readingMinutes: 3,
    tone: "leaf",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=75",
    relatedProductSlugs: [],
    content: [
      { type: "p", text: "We don't use an instant checkout. Instead, every order is confirmed personally so you get accurate stock, pricing, and delivery details." },
      { type: "list", items: ["Browse products or ask the AI assistant", "Send an order inquiry", "The seller confirms availability, total amount, and delivery", "Pay via your preferred method", "Receive your order"] },
      { type: "p", text: "Most inquiries are confirmed within a few hours during store hours." },
    ],
  },
  {
    slug: "building-a-simple-morning-routine",
    title: "Building a Simple Morning Routine",
    excerpt: "Small, realistic habits for calmer mornings, with or without coffee.",
    category: "Lifestyle",
    author: "Rhea Bautista",
    publishedAt: "2026-07-15T09:00:00+08:00",
    readingMinutes: 4,
    tone: "sage",
    image: "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=900&q=75",
    relatedProductSlugs: ["spirulina-cereal", "spica-tea"],
    content: [
      { type: "p", text: "A good morning doesn't need to be complicated. A few consistent habits can make the start of the day feel less rushed." },
      { type: "list", items: ["Prepare your cup and breakfast the night before", "Drink a glass of water when you wake up", "Take five minutes without your phone", "Keep a quick breakfast option ready"] },
      { type: "p", text: "Find what works for your schedule and keep it simple." },
    ],
  },
];

/** Sample feedback for the demo. Replace with real, consented customer reviews before launch. */
export const testimonials: Testimonial[] = [
  { id: "tst_001", name: "Maria S.", location: "Quezon City", quote: "Ang bilis mag-reply! I asked about prices at night and the seller confirmed my order the next morning. Delivery was on time.", productSlug: "lingzhi-coffee-3-in-1" },
  { id: "tst_002", name: "Mark V.", location: "Cainta", quote: "I like that I can just message 'same order' and they already know what I usually get. Very convenient for our office.", productSlug: "lingzhi-black-coffee" },
  { id: "tst_003", name: "Ana C.", location: "Pasig", quote: "The AI assistant helped me compare the drinks before I ordered. My kids like the Cocozhi as a cold chocolate drink.", productSlug: "cocozhi-cocoa-drink" },
  { id: "tst_004", name: "Grace L.", location: "Caloocan", quote: "Rhea sent me the full label details when I asked. Clear answers, no pressure to buy.", productSlug: "rg-reishi-gano" },
];

export const storeFaqs: StoreFAQ[] = [
  { group: "Ordering", question: "How do I order?", answer: "Browse products and send an order inquiry, or ask the AI assistant to prepare one. The seller will confirm availability, total amount, payment, and delivery before anything is processed." },
  { group: "Ordering", question: "Is there an online checkout?", answer: "Not yet. Every order is confirmed personally by the seller so stock and delivery details are accurate." },
  { group: "Ordering", question: "Can I reorder my usual products?", answer: "Yes! Just message \"same order\" in the chat or on Messenger and the seller will prepare your usual order for confirmation." },
  { group: "Delivery & Payment", question: "Where do you deliver?", answer: "We deliver within Metro Manila, Rizal, and Bulacan. Provincial orders can be shipped by courier. The seller confirms the delivery fee after your inquiry." },
  { group: "Delivery & Payment", question: "What payment methods do you accept?", answer: "Cash on delivery (Metro Manila), GCash, Maya, and bank transfer." },
  { group: "Delivery & Payment", question: "How long does delivery take?", answer: "Metro Manila deliveries usually arrive within 1–3 days after confirmation. Courier shipments may take 3–7 days." },
  { group: "Products", question: "Are these official DXN products?", answer: "Products are sourced through an independent DXN distributor. This website is operated by the distributor and is not the official DXN corporate website." },
  { group: "Products", question: "Can these products treat a health condition?", answer: "No. Our products are foods, beverages, supplements, and personal-care items. They are not intended to diagnose, treat, cure, or prevent any disease. Please consult a qualified healthcare professional for medical advice." },
  { group: "Products", question: "Are the prices final?", answer: "Prices shown are reference prices. The seller confirms the final amount, including delivery, before you pay." },
  { group: "AI Assistant", question: "Who am I talking to in the chat?", answer: "An AI assistant that uses the seller's approved product information. It can answer questions and prepare order inquiries. You can ask to talk to the seller at any time." },
  { group: "AI Assistant", question: "Will the AI give medical advice?", answer: "No. For any health or medical question, the assistant will recommend consulting a qualified healthcare professional and can pass your question to the seller." },
  { group: "AI Assistant", question: "What happens to my contact details?", answer: "Your details are only used by the seller to respond to your inquiry. See our Privacy Policy for more information." },
];
