import type { Customer } from "@/types";
import { daysAgo } from "./time";

/**
 * Lifetime orders, value, last order, and reorder predictions are derived from
 * `orders.ts` by the customer service. They are not stored here.
 */
export const customers: Customer[] = [
  {
    id: "cus_001",
    name: "Maria Santos",
    mobile: "0917 555 0101",
    email: "maria.santos@example.com",
    messengerName: "Maria Santos",
    location: "Quezon City",
    status: "vip",
    preferredChannel: "messenger",
    favoriteProducts: ["lingzhi-coffee-3-in-1", "ganozhi-soap"],
    customerSince: daysAgo(210),
    conversationId: "cnv_003",
    notes: ["Prefers delivery on Saturdays.", "Usually orders 3 boxes for the household."],
    aiInsights: [
      "Reorders Lingzhi Coffee 3-in-1 roughly every 40 days.",
      "Always orders in multiples of 3 boxes.",
      "Responds fastest on Messenger in the morning.",
    ],
  },
  {
    id: "cus_002",
    name: "Ana Cruz",
    mobile: "0918 555 0102",
    messengerName: "Ana M. Cruz",
    location: "Pasig",
    status: "active",
    preferredChannel: "sms",
    favoriteProducts: ["cocozhi-cocoa-drink"],
    customerSince: daysAgo(120),
    notes: ["Buys Cocozhi for her kids' baon drinks."],
    aiInsights: ["Orders Cocozhi about every 33 days.", "Due for a reorder around now."],
  },
  {
    id: "cus_003",
    name: "Jenny Mendoza",
    mobile: "0927 555 0103",
    email: "jenny.m@example.com",
    location: "Antipolo",
    status: "at_risk",
    preferredChannel: "sms",
    favoriteProducts: ["white-coffee-zhino"],
    customerSince: daysAgo(150),
    notes: ["Mentioned she might try another brand."],
    aiInsights: [
      "Past her usual reorder window by about 2 weeks.",
      "A friendly check-in may help keep her as a customer.",
    ],
  },
  {
    id: "cus_004",
    name: "Mark Villanueva",
    mobile: "0919 555 0104",
    messengerName: "Mark Villanueva",
    location: "Cainta",
    status: "vip",
    preferredChannel: "messenger",
    favoriteProducts: ["lingzhi-black-coffee"],
    customerSince: daysAgo(180),
    notes: ["Office buyer. Sometimes orders for officemates."],
    aiInsights: ["Very regular: black coffee every ~30 days.", "Could be offered a bulk office bundle."],
  },
  {
    id: "cus_005",
    name: "Paolo Garcia",
    mobile: "0906 555 0105",
    location: "Manila",
    status: "active",
    preferredChannel: "viber",
    favoriteProducts: ["spirulina-tablets"],
    customerSince: daysAgo(20),
    notes: [],
    aiInsights: ["First-time buyer. Check in after 3–4 weeks."],
  },
  {
    id: "cus_006",
    name: "Grace Lim",
    mobile: "0917 555 0106",
    email: "grace.lim@example.com",
    location: "Caloocan",
    status: "active",
    preferredChannel: "email",
    favoriteProducts: ["rg-reishi-gano", "gl-ganocelium"],
    customerSince: daysAgo(90),
    notes: ["Asked for label details before ordering."],
    aiInsights: ["Buys RG and GL together.", "Next reorder expected in about 3 weeks."],
  },
  {
    id: "cus_007",
    name: "Joy Navarro",
    mobile: "0928 555 0107",
    location: "Bulacan",
    status: "inactive",
    preferredChannel: "sms",
    favoriteProducts: ["lingzhi-coffee-3-in-1"],
    customerSince: daysAgo(160),
    notes: ["Moved to Malolos, may need courier delivery."],
    aiInsights: ["No orders in 100 days.", "Consider a win-back message with courier options."],
  },
  {
    id: "cus_008",
    name: "Ramon Aquino",
    mobile: "0916 555 0108",
    location: "Quezon City",
    status: "active",
    preferredChannel: "mobile",
    favoriteProducts: ["ganozhi-soap", "ganozhi-toothpaste"],
    customerSince: daysAgo(60),
    notes: ["Prefers a phone call over chat."],
    aiInsights: ["Buys personal-care bundles.", "Likely to reorder soap within a week."],
  },
  {
    id: "cus_009",
    name: "Teresa Flores",
    mobile: "0917 555 0109",
    messengerName: "Tess Flores",
    location: "Pasig",
    status: "active",
    preferredChannel: "messenger",
    favoriteProducts: ["cocozhi-cocoa-drink", "lingzhi-coffee-3-in-1"],
    customerSince: daysAgo(8),
    leadId: "led_015",
    notes: [],
    aiInsights: ["New customer from the website AI chat.", "Received her first order 1 week ago."],
  },
  {
    id: "cus_010",
    name: "Liza Tan",
    mobile: "0918 555 0110",
    email: "liza.tan@example.com",
    location: "Makati",
    status: "active",
    preferredChannel: "email",
    favoriteProducts: ["cordyceps-coffee-3-in-1"],
    customerSince: daysAgo(70),
    notes: [],
    aiInsights: ["Slightly past her usual cycle for Cordyceps Coffee.", "Stock is low: confirm availability before reaching out."],
  },
  {
    id: "cus_011",
    name: "Camille Sy",
    mobile: "0917 555 0111",
    location: "Taguig",
    status: "active",
    preferredChannel: "viber",
    favoriteProducts: ["lingzhi-black-coffee"],
    customerSince: daysAgo(2),
    leadId: "led_010",
    notes: ["Referred by Mark Villanueva."],
    aiInsights: ["Converted from a referral. First order confirmed."],
  },
  {
    id: "cus_012",
    name: "Arnel Mercado",
    mobile: "0999 555 0112",
    location: "Pasay",
    status: "active",
    preferredChannel: "mobile",
    favoriteProducts: ["rg-reishi-gano", "gl-ganocelium"],
    customerSince: daysAgo(1),
    leadId: "led_011",
    notes: [],
    aiInsights: ["Converted from the website AI chat after asking about RG and GL."],
  },
  {
    id: "cus_013",
    name: "Lovely Manalo",
    mobile: "0935 555 0113",
    messengerName: "Lovely Manalo",
    location: "Bulacan",
    status: "active",
    preferredChannel: "messenger",
    favoriteProducts: ["spirulina-cereal"],
    customerSince: daysAgo(4),
    leadId: "led_012",
    conversationId: "cnv_009",
    notes: ["Shipped via courier to Meycauayan."],
    aiInsights: ["Asked about delivery status. Escalated to you."],
  },
];
