import type { FollowUp } from "@/types";
import { hoursAgo, manilaDayAt } from "./time";

export const followUps: FollowUp[] = [
  {
    id: "fup_001",
    customerName: "Maria Santos",
    customerId: "cus_001",
    productSlug: "lingzhi-coffee-3-in-1",
    reason: "reorder_reminder",
    reasonDetail: "Last order 35 days ago. Usually reorders every ~40 days. She messaged about reordering today.",
    channel: "messenger",
    scheduledAt: manilaDayAt(0, 10),
    suggestedMessage:
      "Hi Maria! Rhea here. Confirming your reorder: 3 boxes of Lingzhi Coffee 3-in-1 for Saturday delivery to QC. Total is ₱1,950 + delivery. Okay po ba?",
    suggestedAction: "Confirm reorder details and delivery day.",
    status: "scheduled",
    createdBy: "ai",
  },
  {
    id: "fup_002",
    customerName: "Kristine Bautista",
    leadId: "led_001",
    productSlug: "lingzhi-coffee-3-in-1",
    reason: "incomplete_inquiry",
    reasonDetail: "Asked about 3 boxes but did not complete inquiry.",
    channel: "sms",
    scheduledAt: manilaDayAt(0, 14),
    suggestedMessage:
      "Hi Kristine! This is Rhea from Luntian Wellness. Following up on the 3 boxes of Lingzhi Coffee 3-in-1. Delivery to Quezon City is ₱80, so the total would be ₱2,030. Would you like me to reserve them for you?",
    suggestedAction: "Send friendly follow-up.",
    status: "scheduled",
    createdBy: "ai",
  },
  {
    id: "fup_003",
    customerName: "Carlo Reyes",
    leadId: "led_002",
    productSlug: "lingzhi-black-coffee",
    reason: "product_comparison",
    reasonDetail: "Compared Black Coffee and 3-in-1. Prefers less sweet coffee. Said he'd think about it.",
    channel: "messenger",
    scheduledAt: manilaDayAt(1, 11),
    suggestedMessage:
      "Hi Carlo! Just checking in. Since you prefer less sweet coffee, Lingzhi Black Coffee might be a great fit. Want to try 1 box first?",
    suggestedAction: "Recommend Black Coffee and offer a single box to try.",
    status: "scheduled",
    createdBy: "ai",
  },
  {
    id: "fup_004",
    customerName: "Ana Cruz",
    customerId: "cus_002",
    productSlug: "cocozhi-cocoa-drink",
    reason: "reorder_reminder",
    reasonDetail: "Previous customer. Potential reorder: Cocozhi every ~33 days, last order 33 days ago.",
    channel: "sms",
    scheduledAt: manilaDayAt(1, 9),
    suggestedMessage:
      "Hi Ana! Rhea here. Your kids' Cocozhi might be running low. Would you like me to prepare 2 boxes again this week?",
    suggestedAction: "Offer a reorder of 2 boxes of Cocozhi.",
    status: "scheduled",
    createdBy: "ai",
  },
  {
    id: "fup_005",
    customerName: "Jomar Dizon",
    leadId: "led_006",
    productSlug: "cordyceps-coffee-3-in-1",
    reason: "price_objection",
    reasonDetail: "Felt Cordyceps Coffee was expensive.",
    channel: "messenger",
    scheduledAt: manilaDayAt(3, 15),
    suggestedMessage:
      "Hi Jomar! If you'd like to try our coffee without committing to a lot, you can start with 1 box of Lingzhi Coffee 3-in-1 (₱650, 20 cups).",
    suggestedAction: "Offer a lower-priced alternative.",
    status: "scheduled",
    createdBy: "seller",
  },
  {
    id: "fup_006",
    customerName: "Bea Santiago",
    leadId: "led_004",
    productSlug: "white-coffee-zhino",
    reason: "payment_pending",
    reasonDetail: "GCash details sent yesterday. No payment screenshot received yet.",
    channel: "messenger",
    scheduledAt: manilaDayAt(-1, 16),
    suggestedMessage:
      "Hi Bea! Gentle reminder for your order (3 White Coffee + 2 Soap). Once you've sent the GCash payment, just send a screenshot and I'll schedule delivery. Salamat!",
    suggestedAction: "Send a gentle payment reminder.",
    status: "scheduled",
    createdBy: "ai",
  },
  {
    id: "fup_007",
    customerName: "Jenny Mendoza",
    customerId: "cus_003",
    productSlug: "white-coffee-zhino",
    reason: "reorder_reminder",
    reasonDetail: "About 2 weeks past her usual reorder cycle. Marked at risk.",
    channel: "sms",
    scheduledAt: manilaDayAt(-2, 10),
    suggestedMessage:
      "Hi Jenny! Rhea here. Kumusta? Just checking if you need White Coffee Zhino this month. I can deliver to Antipolo this week.",
    suggestedAction: "Friendly check-in; no hard sell.",
    status: "scheduled",
    createdBy: "ai",
  },
  {
    id: "fup_008",
    customerName: "Hazel Robles",
    leadId: "led_013",
    productSlug: "spica-tea",
    reason: "incomplete_inquiry",
    reasonDetail: "Interested in Spica Tea but hesitant to buy a full box.",
    channel: "sms",
    scheduledAt: manilaDayAt(2, 10),
    suggestedMessage:
      "Hi Hazel! If you'd like a light evening drink, Spica Tea is ₱450 for 20 tea bags. I can add it to a small order for you.",
    suggestedAction: "Suggest bundling Spica Tea.",
    status: "scheduled",
    createdBy: "ai",
  },
  {
    id: "fup_009",
    customerName: "Patricia Ramos",
    leadId: "led_005",
    productSlug: "cocozhi-cocoa-drink",
    reason: "general",
    reasonDetail: "Asked about Cocozhi for her kids.",
    channel: "messenger",
    scheduledAt: manilaDayAt(4, 17),
    suggestedMessage:
      "Hi Patricia! Here's the full ingredient list for Cocozhi. Let me know if you'd like to order a box.",
    suggestedAction: "Share ingredients and ask about quantity.",
    status: "scheduled",
    createdBy: "ai",
  },
  {
    id: "fup_010",
    customerName: "Teresa Flores",
    customerId: "cus_009",
    reason: "post_delivery_check",
    reasonDetail: "First order delivered a week ago.",
    channel: "messenger",
    scheduledAt: manilaDayAt(-1, 10),
    suggestedMessage: "Hi Tess! How did you like the Cocozhi and Lingzhi Coffee? Let me know if you have any questions.",
    suggestedAction: "Post-delivery check-in.",
    status: "completed",
    completedAt: hoursAgo(26),
    createdBy: "ai",
  },
  {
    id: "fup_011",
    customerName: "Grace Lim",
    customerId: "cus_006",
    productSlug: "rg-reishi-gano",
    reason: "post_delivery_check",
    reasonDetail: "Order delivered 10 days ago.",
    channel: "email",
    scheduledAt: manilaDayAt(-5, 9),
    suggestedMessage: "Hi Grace! Just checking that your RG arrived safely. Let me know if you need anything.",
    suggestedAction: "Post-delivery check-in.",
    status: "completed",
    completedAt: hoursAgo(24 * 5),
    createdBy: "seller",
  },
  {
    id: "fup_012",
    customerName: "Camille Sy",
    leadId: "led_010",
    customerId: "cus_011",
    productSlug: "lingzhi-black-coffee",
    reason: "payment_pending",
    reasonDetail: "Waiting for GCash payment.",
    channel: "viber",
    scheduledAt: manilaDayAt(-2, 15),
    suggestedMessage: "Hi Camille! Reminder for your Black Coffee order payment.",
    suggestedAction: "Payment reminder.",
    status: "completed",
    completedAt: hoursAgo(40),
    createdBy: "ai",
  },
];
