import type { Lead, TimelineEvent, TimelineEventType } from "@/types";
import { hoursAgo, hoursFromNow, manilaDayAt } from "./time";

type EventSeed = [type: TimelineEventType, title: string, hoursAgo: number, description?: string];

function timeline(leadId: string, events: EventSeed[]): TimelineEvent[] {
  return events
    .map(([type, title, h, description], i) => ({
      id: `${leadId}_evt_${i + 1}`,
      type,
      title,
      description,
      timestamp: hoursAgo(h),
    }))
    .sort((a, b) => b.timestamp.localeCompare(a.timestamp));
}

const SELLER = "Rhea Bautista";

export const leads: Lead[] = [
  {
    id: "led_001",
    name: "Kristine Bautista",
    mobile: "0917 123 4567",
    location: "Quezon City",
    source: "website_chat",
    interests: [{ productSlug: "lingzhi-coffee-3-in-1", quantity: 3 }],
    leadScore: 87,
    purchaseIntent: "high",
    lastIntent: "shipping_inquiry",
    stage: "interested",
    preferredChannel: "sms",
    objections: ["Hasn't confirmed the order yet", "Asked about the delivery fee"],
    aiSummary:
      "Customer asked about 3 boxes of Lingzhi Coffee and provided location information but did not confirm the order. Follow up within 24 hours.",
    recommendedAction: "Send the total with delivery fee for Quezon City and offer to create the order inquiry.",
    lastActivityAt: hoursAgo(3),
    nextFollowUpAt: manilaDayAt(0, 14),
    assignedTo: SELLER,
    createdAt: hoursAgo(4),
    conversationId: "cnv_001",
    notes: [],
    timeline: timeline("led_001", [
      ["website_visit", "Visited Lingzhi Coffee 3-in-1 page", 4.2, "Came from a Facebook post"],
      ["customer_message", "Asked for the price of Lingzhi Coffee", 4, "\"Magkano Lingzhi Coffee? Maybe kukuha ako tatlo.\""],
      ["ai_message", "AI confirmed quantity and asked for location", 3.95],
      ["customer_message", "Shared location: Quezon City", 3.5],
      ["ai_message", "AI captured name and mobile number", 3.2],
      ["stage_change", "Stage changed to Interested", 3.1, "High purchase intent detected (3 boxes)"],
      ["follow_up", "AI scheduled a follow-up for today, 2:00 PM", 3],
    ]),
  },
  {
    id: "led_002",
    name: "Carlo Reyes",
    messengerName: "Carlo Reyes",
    mobile: "0917 555 0202",
    location: "Makati",
    source: "messenger",
    interests: [{ productSlug: "lingzhi-black-coffee" }, { productSlug: "lingzhi-coffee-3-in-1" }],
    leadScore: 72,
    purchaseIntent: "medium",
    lastIntent: "product_comparison",
    stage: "qualified",
    preferredChannel: "messenger",
    objections: ["Undecided between black coffee and 3-in-1", "Doesn't like very sweet coffee"],
    aiSummary:
      "Comparing Lingzhi Black Coffee and 3-in-1. Prefers less sweet coffee, so Black Coffee is the likely fit. Said he'd think about it.",
    recommendedAction: "Follow up tomorrow suggesting Black Coffee, with the option to add sweetener himself.",
    lastActivityAt: hoursAgo(20),
    nextFollowUpAt: manilaDayAt(1, 11),
    assignedTo: SELLER,
    createdAt: hoursAgo(26),
    conversationId: "cnv_002",
    notes: ["Works in BGC, may want office delivery."],
    timeline: timeline("led_002", [
      ["customer_message", "Asked about the difference between black coffee and 3-in-1", 22],
      ["ai_message", "AI compared both products", 21.9],
      ["customer_message", "Said he doesn't like sweet coffee", 21],
      ["ai_message", "AI recommended Lingzhi Black Coffee", 20.9],
      ["stage_change", "Stage changed to Qualified", 20.5],
      ["follow_up", "AI scheduled a follow-up for tomorrow", 20],
    ]),
  },
  {
    id: "led_003",
    name: "Enzo Castillo",
    mobile: "0917 555 0203",
    email: "enzo.c@example.com",
    location: "Taguig",
    source: "order_form",
    interests: [{ productSlug: "spirulina-tablets", quantity: 2 }],
    leadScore: 91,
    purchaseIntent: "high",
    lastIntent: "buy_product",
    stage: "order_inquiry",
    preferredChannel: "sms",
    objections: [],
    aiSummary: "Submitted an order inquiry for 2 bottles of Spirulina Tablets. Asked if Saturday pick-up is possible.",
    recommendedAction: "Confirm availability and Saturday pick-up schedule by SMS.",
    lastActivityAt: hoursAgo(5),
    assignedTo: SELLER,
    createdAt: hoursAgo(6),
    notes: [],
    timeline: timeline("led_003", [
      ["website_visit", "Browsed Food Supplements", 6],
      ["inquiry", "Sent an order inquiry: Spirulina Tablets × 2", 5, "Order LW-10263"],
    ]),
  },
  {
    id: "led_004",
    name: "Bea Santiago",
    messengerName: "Bea Santiago",
    mobile: "0921 555 0204",
    location: "Marikina",
    source: "messenger",
    interests: [
      { productSlug: "white-coffee-zhino", quantity: 3 },
      { productSlug: "ganozhi-soap", quantity: 2 },
    ],
    leadScore: 84,
    purchaseIntent: "high",
    lastIntent: "buy_product",
    stage: "order_inquiry",
    preferredChannel: "messenger",
    objections: ["Payment not yet sent"],
    aiSummary: "Order inquiry for 3 White Coffee Zhino and 2 Ganozhi Soap. Chose GCash but hasn't sent payment.",
    recommendedAction: "Send a gentle payment reminder with the GCash details.",
    lastActivityAt: hoursAgo(18),
    nextFollowUpAt: manilaDayAt(-1, 16),
    assignedTo: SELLER,
    createdAt: hoursAgo(30),
    conversationId: "cnv_005",
    notes: [],
    timeline: timeline("led_004", [
      ["customer_message", "Asked if White Coffee is available", 30],
      ["ai_message", "AI confirmed availability and recommended adding soap", 29.9],
      ["inquiry", "Order inquiry created: White Coffee × 3, Soap × 2", 22],
      ["seller_message", "Rhea sent GCash payment details", 18],
    ]),
  },
  {
    id: "led_005",
    name: "Patricia Ramos",
    location: "Mandaluyong",
    source: "website_chat",
    interests: [{ productSlug: "cocozhi-cocoa-drink" }],
    leadScore: 58,
    purchaseIntent: "medium",
    lastIntent: "product_inquiry",
    stage: "engaged",
    preferredChannel: "messenger",
    objections: ["Asked whether it's suitable for kids"],
    aiSummary: "Interested in Cocozhi as a drink for her children. AI shared ingredients and suggested asking a pediatrician about specific concerns.",
    recommendedAction: "Share the ingredient list and ask how many boxes she'd like.",
    lastActivityAt: hoursAgo(9),
    nextFollowUpAt: hoursFromNow(96),
    assignedTo: SELLER,
    createdAt: hoursAgo(10),
    conversationId: "cnv_006",
    notes: [],
    timeline: timeline("led_005", [
      ["website_visit", "Viewed Cocozhi Cocoa Drink", 10],
      ["customer_message", "Asked if Cocozhi is okay for kids", 9.5],
      ["ai_message", "AI shared ingredients and a pediatrician note", 9.4],
    ]),
  },
  {
    id: "led_006",
    name: "Jomar Dizon",
    messengerName: "jomar.dzn",
    location: "Caloocan",
    source: "instagram",
    interests: [{ productSlug: "cordyceps-coffee-3-in-1" }],
    leadScore: 45,
    purchaseIntent: "medium",
    lastIntent: "price_inquiry",
    stage: "engaged",
    preferredChannel: "messenger",
    objections: ["Price concern: thinks it's more expensive than store coffee"],
    aiSummary: "Asked about Cordyceps Coffee price and said it's pricier than regular 3-in-1.",
    recommendedAction: "Explain the per-cup cost and offer to start with 1 box.",
    lastActivityAt: hoursAgo(28),
    nextFollowUpAt: hoursFromNow(72),
    assignedTo: SELLER,
    createdAt: hoursAgo(30),
    conversationId: "cnv_007",
    notes: [],
    timeline: timeline("led_006", [
      ["customer_message", "Asked the price of Cordyceps Coffee on Instagram", 30],
      ["ai_message", "AI shared reference price and per-cup cost", 29.9],
      ["customer_message", "Said it's a bit expensive", 28],
    ]),
  },
  {
    id: "led_007",
    name: "Miguel Torres",
    location: "Antipolo",
    source: "website_chat",
    interests: [{ productSlug: "rg-reishi-gano" }],
    leadScore: 38,
    purchaseIntent: "low",
    lastIntent: "medical_question",
    stage: "engaged",
    preferredChannel: "sms",
    objections: ["Asked a health-related question (escalated)"],
    aiSummary: "Asked whether RG is okay with his maintenance medicine. AI did not give medical advice, suggested consulting his doctor, and escalated.",
    recommendedAction: "Reply personally. Share label information only and encourage him to check with his doctor.",
    lastActivityAt: hoursAgo(2),
    assignedTo: SELLER,
    createdAt: hoursAgo(2.5),
    conversationId: "cnv_004",
    notes: [],
    timeline: timeline("led_007", [
      ["website_visit", "Viewed RG (Reishi Gano) Capsules", 2.5],
      ["customer_message", "Asked if RG is okay with maintenance medicine", 2.2],
      ["ai_message", "AI referred him to a healthcare professional", 2.15],
      ["stage_change", "Escalated to seller", 2.1, "Health-related question guardrail"],
    ]),
  },
  {
    id: "led_008",
    name: "Rina Pascual",
    messengerName: "rinapascual",
    source: "tiktok",
    interests: [],
    leadScore: 22,
    purchaseIntent: "low",
    lastIntent: "general_question",
    stage: "new",
    preferredChannel: "messenger",
    objections: [],
    aiSummary: "Asked where the store is based after seeing a TikTok video. No product interest yet.",
    recommendedAction: "Share the product catalog link and ask what she usually drinks in the morning.",
    lastActivityAt: hoursAgo(12),
    assignedTo: SELLER,
    createdAt: hoursAgo(12),
    notes: [],
    timeline: timeline("led_008", [["customer_message", "Asked where the store is located", 12]]),
  },
  {
    id: "led_009",
    name: "Dennis Ocampo",
    messengerName: "Dennis Ocampo",
    mobile: "0998 555 0209",
    location: "Valenzuela",
    source: "facebook",
    interests: [{ productSlug: "lingzhi-coffee-3-in-1", quantity: 10 }],
    leadScore: 30,
    purchaseIntent: "low",
    lastIntent: "complaint",
    stage: "lost",
    preferredChannel: "messenger",
    objections: ["Found another supplier"],
    aiSummary: "Wanted 10 boxes for resale but cancelled after finding another supplier.",
    recommendedAction: "No action needed. Optionally check in next month.",
    lastActivityAt: hoursAgo(24 * 6),
    assignedTo: SELLER,
    createdAt: hoursAgo(24 * 8),
    notes: ["Reseller. Price-sensitive."],
    timeline: timeline("led_009", [
      ["inquiry", "Order inquiry: Lingzhi Coffee 3-in-1 × 10", 24 * 8],
      ["order", "Order cancelled by customer", 24 * 6, "Found another supplier"],
      ["stage_change", "Marked as Lost", 24 * 6],
    ]),
  },
  {
    id: "led_010",
    name: "Camille Sy",
    mobile: "0917 555 0111",
    location: "Taguig",
    source: "referral",
    interests: [{ productSlug: "lingzhi-black-coffee", quantity: 2 }],
    leadScore: 95,
    purchaseIntent: "high",
    lastIntent: "buy_product",
    stage: "converted",
    preferredChannel: "viber",
    objections: [],
    aiSummary: "Referred by Mark Villanueva. Ordered 2 boxes of Black Coffee; order confirmed.",
    recommendedAction: "Check in after delivery and thank Mark for the referral.",
    lastActivityAt: hoursAgo(40),
    assignedTo: SELLER,
    createdAt: hoursAgo(50),
    customerId: "cus_011",
    notes: [],
    timeline: timeline("led_010", [
      ["inquiry", "Order inquiry: Black Coffee × 2", 46],
      ["order", "Order confirmed", 40],
      ["stage_change", "Converted to customer", 40],
    ]),
  },
  {
    id: "led_011",
    name: "Arnel Mercado",
    mobile: "0999 555 0112",
    location: "Pasay",
    source: "website_chat",
    interests: [{ productSlug: "rg-reishi-gano", quantity: 1 }, { productSlug: "gl-ganocelium", quantity: 1 }],
    leadScore: 90,
    purchaseIntent: "high",
    lastIntent: "buy_product",
    stage: "converted",
    preferredChannel: "mobile",
    objections: [],
    aiSummary: "Asked about the difference between RG and GL, then ordered one of each.",
    recommendedAction: "Order is being prepared. Send delivery ETA.",
    lastActivityAt: hoursAgo(20),
    assignedTo: SELLER,
    createdAt: hoursAgo(32),
    customerId: "cus_012",
    notes: [],
    timeline: timeline("led_011", [
      ["customer_message", "Asked about RG vs GL", 32],
      ["ai_message", "AI compared RG and GL using approved label info", 31.9],
      ["inquiry", "Order inquiry: RG × 1, GL × 1", 30],
      ["stage_change", "Converted to customer", 24],
    ]),
  },
  {
    id: "led_012",
    name: "Lovely Manalo",
    messengerName: "Lovely Manalo",
    mobile: "0935 555 0113",
    location: "Bulacan",
    source: "facebook",
    interests: [{ productSlug: "spirulina-cereal", quantity: 4 }],
    leadScore: 88,
    purchaseIntent: "high",
    lastIntent: "complaint",
    stage: "converted",
    preferredChannel: "messenger",
    objections: ["Delivery taking longer than expected"],
    aiSummary: "Converted customer. Asked where her courier delivery is. Escalated for a personal update.",
    recommendedAction: "Check courier tracking and update her today.",
    lastActivityAt: hoursAgo(1),
    assignedTo: SELLER,
    createdAt: hoursAgo(24 * 5),
    customerId: "cus_013",
    conversationId: "cnv_009",
    notes: [],
    timeline: timeline("led_012", [
      ["inquiry", "Order inquiry: Spirulina Cereal × 4", 24 * 4],
      ["order", "Order shipped via courier", 24 * 2],
      ["customer_message", "Asked about delivery status", 1],
      ["stage_change", "Escalated to seller", 0.9, "Complaint guardrail"],
    ]),
  },
  {
    id: "led_013",
    name: "Hazel Robles",
    mobile: "0917 555 0213",
    location: "Cainta",
    source: "website_chat",
    interests: [{ productSlug: "spica-tea" }],
    leadScore: 66,
    purchaseIntent: "medium",
    lastIntent: "product_inquiry",
    stage: "qualified",
    preferredChannel: "sms",
    objections: ["Wants to try before buying a full box"],
    aiSummary: "Looking for a light evening drink. Interested in Spica Tea but hesitant to commit to a full box.",
    recommendedAction: "Offer to bundle 1 box of Spica Tea with her next order.",
    lastActivityAt: hoursAgo(15),
    nextFollowUpAt: hoursFromNow(48),
    assignedTo: SELLER,
    createdAt: hoursAgo(16),
    notes: [],
    timeline: timeline("led_013", [
      ["customer_message", "Asked for a light drink for the evening", 16],
      ["ai_message", "AI recommended Spica Tea", 15.9],
      ["ai_message", "AI captured mobile number", 15],
    ]),
  },
  {
    id: "led_014",
    name: "Nico Fernandez",
    messengerName: "Nico Fernandez",
    location: "Pasig",
    source: "messenger",
    interests: [{ productSlug: "ganozhi-shampoo", quantity: 2 }],
    leadScore: 50,
    purchaseIntent: "medium",
    lastIntent: "availability_inquiry",
    stage: "interested",
    preferredChannel: "messenger",
    objections: ["Product out of stock"],
    aiSummary: "Wants 2 bottles of Ganozhi Shampoo, which is currently out of stock. Asked to be notified.",
    recommendedAction: "Notify him when shampoo is restocked.",
    lastActivityAt: hoursAgo(50),
    assignedTo: SELLER,
    createdAt: hoursAgo(52),
    conversationId: "cnv_008",
    notes: [],
    timeline: timeline("led_014", [
      ["customer_message", "Asked if shampoo is available", 52],
      ["ai_message", "AI said it's restocking and offered a notification", 51.9],
    ]),
  },
  {
    id: "led_015",
    name: "Teresa Flores",
    messengerName: "Tess Flores",
    mobile: "0917 555 0109",
    location: "Pasig",
    source: "website_chat",
    interests: [{ productSlug: "cocozhi-cocoa-drink", quantity: 1 }, { productSlug: "lingzhi-coffee-3-in-1", quantity: 1 }],
    leadScore: 92,
    purchaseIntent: "high",
    lastIntent: "buy_product",
    stage: "converted",
    preferredChannel: "messenger",
    objections: [],
    aiSummary: "Converted through the website AI chat. First order delivered.",
    recommendedAction: "Ask how she liked the products and note her favorite.",
    lastActivityAt: hoursAgo(24 * 7),
    assignedTo: SELLER,
    createdAt: hoursAgo(24 * 9),
    customerId: "cus_009",
    notes: [],
    timeline: timeline("led_015", [
      ["customer_message", "Asked for a coffee recommendation", 24 * 9],
      ["inquiry", "Order inquiry: Cocozhi × 1, Lingzhi 3-in-1 × 1", 24 * 8],
      ["order", "Order delivered", 24 * 7],
      ["stage_change", "Converted to customer", 24 * 7],
    ]),
  },
];
