import type { Campaign, ContentItem } from "@/types";
import { daysAgo, daysFromNow } from "./time";

export const campaigns: Campaign[] = [
  {
    id: "cmp_001",
    name: "Coffee Awareness Campaign",
    objective: "Introduce the coffee line to new customers and drive AI chat conversations.",
    productSlugs: ["lingzhi-coffee-3-in-1", "lingzhi-black-coffee", "white-coffee-zhino"],
    targetAudience: "Working adults 25–45 in Metro Manila who drink instant coffee daily",
    channels: ["facebook", "instagram", "tiktok"],
    status: "active",
    startDate: daysAgo(21),
    endDate: daysFromNow(9),
    funnel: { impressions: 48200, visits: 3120, conversations: 486, leads: 142, orders: 38 },
    estimatedRevenue: 41800,
  },
  {
    id: "cmp_002",
    name: "Reorder Reminder Program",
    objective: "Bring back existing customers before they run out.",
    productSlugs: ["lingzhi-coffee-3-in-1", "cocozhi-cocoa-drink", "lingzhi-black-coffee"],
    targetAudience: "Customers with at least one order in the last 120 days",
    channels: ["messenger_broadcast"],
    status: "active",
    startDate: daysAgo(45),
    funnel: { impressions: 610, visits: 190, conversations: 164, leads: 96, orders: 71 },
    estimatedRevenue: 58400,
  },
  {
    id: "cmp_003",
    name: "Personal Care Starter Bundle",
    objective: "Cross-sell soap and toothpaste to coffee customers.",
    productSlugs: ["ganozhi-soap", "ganozhi-toothpaste"],
    targetAudience: "Existing coffee customers",
    channels: ["facebook", "messenger_broadcast"],
    status: "paused",
    startDate: daysAgo(30),
    funnel: { impressions: 12400, visits: 820, conversations: 104, leads: 31, orders: 12 },
    estimatedRevenue: 6200,
  },
  {
    id: "cmp_004",
    name: "Christmas Gift Boxes",
    objective: "Pre-sell coffee and cocoa gift bundles for the holidays.",
    productSlugs: ["cocozhi-cocoa-drink", "white-coffee-zhino", "lingzhi-coffee-3-in-1"],
    targetAudience: "Office buyers and families preparing Christmas gifts",
    channels: ["facebook", "instagram", "blog"],
    status: "draft",
    startDate: daysFromNow(14),
    funnel: { impressions: 0, visits: 0, conversations: 0, leads: 0, orders: 0 },
    estimatedRevenue: 0,
  },
  {
    id: "cmp_005",
    name: "Back-to-Routine Breakfast",
    objective: "Promote Spirulina Cereal and coffee as quick breakfast options.",
    productSlugs: ["spirulina-cereal", "lingzhi-black-coffee"],
    targetAudience: "Parents and students during school opening",
    channels: ["facebook", "tiktok", "educational"],
    status: "completed",
    startDate: daysAgo(100),
    endDate: daysAgo(60),
    funnel: { impressions: 26800, visits: 1540, conversations: 210, leads: 64, orders: 22 },
    estimatedRevenue: 15900,
  },
];

export const contentItems: ContentItem[] = [
  {
    id: "cnt_001",
    title: "Black vs 3-in-1: Which coffee fits your mornings?",
    platform: "facebook",
    campaignId: "cmp_001",
    status: "published",
    body: "Hindi ka sure kung black coffee o 3-in-1? ☕ Black coffee = simple, bold, no sugar. 3-in-1 = creamy and ready to drink. Ask our AI assistant anytime to compare! Link in comments.",
    createdAt: daysAgo(18),
    publishedAt: daysAgo(17),
    aiGenerated: true,
    metrics: { reach: 12400, engagements: 860, clicks: 410, leads: 38 },
  },
  {
    id: "cnt_002",
    title: "Iced coffee in 60 seconds",
    platform: "tiktok",
    campaignId: "cmp_001",
    status: "published",
    body: "Hook: \"Iced coffee without a coffee shop?\"\n1. Dissolve 1 sachet of Lingzhi 3-in-1 in 50ml hot water\n2. Add ice + cold water\n3. Stir and enjoy\nCTA: Ask our AI assistant which coffee suits you.",
    createdAt: daysAgo(14),
    publishedAt: daysAgo(12),
    aiGenerated: true,
    metrics: { reach: 21800, engagements: 1940, clicks: 520, leads: 44 },
  },
  {
    id: "cnt_003",
    title: "Coffee break aesthetic",
    platform: "instagram",
    campaignId: "cmp_001",
    status: "published",
    body: "Slow mornings, warm cups. ☕🌿 Which one's your go-to: Black, 3-in-1, or White? Comment below! #coffeetime #everydaycup",
    createdAt: daysAgo(10),
    publishedAt: daysAgo(9),
    aiGenerated: false,
    metrics: { reach: 6800, engagements: 540, clicks: 130, leads: 12 },
  },
  {
    id: "cnt_004",
    title: "Reorder reminder: Lingzhi 3-in-1",
    platform: "messenger_broadcast",
    campaignId: "cmp_002",
    status: "approved",
    body: "Hi {first_name}! Rhea here from Luntian Wellness. If your coffee is running low, reply ORDER and I'll prepare your usual. Salamat! 😊",
    createdAt: daysAgo(3),
    aiGenerated: true,
  },
  {
    id: "cnt_005",
    title: "How to Store Your Coffee Products Properly",
    platform: "blog",
    status: "published",
    body: "A practical guide on keeping sachets fresh in humid Philippine weather.",
    createdAt: daysAgo(25),
    publishedAt: daysAgo(22),
    aiGenerated: false,
    metrics: { reach: 2100, engagements: 180, clicks: 240, leads: 9 },
  },
  {
    id: "cnt_006",
    title: "Reading product labels 101",
    platform: "educational",
    status: "draft",
    body: "Carousel: 1) Net content 2) Ingredients list order 3) Storage instructions 4) Registration details 5) Ask us if unsure!",
    createdAt: daysAgo(2),
    aiGenerated: true,
  },
  {
    id: "cnt_007",
    title: "Christmas gift box teaser",
    platform: "facebook",
    campaignId: "cmp_004",
    status: "idea",
    body: "Teaser post for holiday coffee & cocoa gift boxes. Show 3 bundle options and ask followers to vote.",
    createdAt: daysAgo(1),
    aiGenerated: false,
  },
  {
    id: "cnt_008",
    title: "Soap + toothpaste starter bundle",
    platform: "instagram",
    campaignId: "cmp_003",
    status: "draft",
    body: "Complete your daily routine 🌿 Ganozhi Soap + Toothpaste bundle. Message us to add it to your next coffee order.",
    createdAt: daysAgo(6),
    aiGenerated: true,
  },
  {
    id: "cnt_009",
    title: "Cocozhi merienda idea",
    platform: "tiktok",
    status: "idea",
    body: "Show a simple after-school cold chocolate drink using Cocozhi. Keep it fun, no health claims.",
    createdAt: daysAgo(4),
    aiGenerated: true,
  },
  {
    id: "cnt_010",
    title: "Breakfast in 2 minutes",
    platform: "facebook",
    campaignId: "cmp_005",
    status: "published",
    body: "Busy mornings? Spirulina Cereal + a cup of black coffee = breakfast in 2 minutes. ⏱️",
    createdAt: daysAgo(90),
    publishedAt: daysAgo(88),
    aiGenerated: false,
    metrics: { reach: 9400, engagements: 610, clicks: 290, leads: 21 },
  },
];
