import type { Product } from "@/types";
import { daysAgo } from "./time";

const SHIPPING_INFO =
  "Delivery is available within Metro Manila, Rizal, and Bulacan. Provincial shipping can be arranged by courier. The seller confirms stock, delivery fee, and schedule after you send an inquiry. Pick-up in Pasig is available by appointment.";

const FOOD_NOTICE =
  "This is a food/beverage product. It is not intended to diagnose, treat, cure, or prevent any disease. If you are pregnant, nursing, taking medication, or have a medical condition, consult a qualified healthcare professional before use.";

const SUPPLEMENT_NOTICE =
  "MAHALAGANG PAALALA: This is a food supplement and is not a medicine. It should not be used as a replacement for medication or to treat any disease. No approved therapeutic claims. Consult a qualified healthcare professional before use, especially if you are pregnant, nursing, or under medical treatment.";

const PERSONAL_CARE_NOTICE =
  "For external use only (soap and shampoo). Discontinue use if irritation occurs. Keep out of reach of children. Perform a patch test if you have sensitive skin.";

const PACKAGING_REF = { label: "Registration details", value: "Refer to official product packaging" };

const IMAGES: Record<string, string[]> = {
  "lingzhi-black-coffee": [
    "https://f.nooncdn.com/p/pzsku/Z808B55B620DFD6B2C44FZ/45/1758031984/a129f008-d4b4-46e1-a071-fe45441802a5.jpg",
    "https://f.nooncdn.com/p/pzsku/ZBD0E90B59FBF314FFEC9Z/45/1746876270/3a103547-78fd-4cd2-8894-08c7a82a8461.jpg",
    "https://f.nooncdn.com/p/pzsku/ZBD0E90B59FBF314FFEC9Z/45/1746876270/dc12febd-4f38-4bfa-829c-b90c1aab3bcc.jpg",
    "https://f.nooncdn.com/p/pzsku/ZBD0E90B59FBF314FFEC9Z/45/1746876270/8729cc4a-4e7c-46de-836c-032183d907e8.jpg",
  ],
  "lingzhi-coffee-3-in-1": [
    "https://i.ebayimg.com/images/g/AwoAAeSwd5NpDPNM/s-l1200.jpg",
    "https://f.nooncdn.com/p/pzsku/ZC89493635C506AD5CC61Z/45/1747317842/c878cf79-77e1-47d3-9bc4-f493ab6de760.jpg",
    "https://f.nooncdn.com/p/pzsku/ZC4F00930F52ABD299812Z/45/_/1734263642/d7b61234-cb9e-4749-858c-fa6e1e3a30fa.jpg",
  ],
  "white-coffee-zhino": [
    "https://alibooster.com/60-large_default/dxn-white-coffee-soluble-zhino-coffee-mushroom-ganoderma-12-x-28-grams.jpg",
    "https://ganodermabolt.hu/img/24064/FB098/500x500/DXN-White-Coffee-Zhino.jpg?time=1680001321",
    "https://alibooster.com/61-home_default/dxn-white-coffee-soluble-zhino-coffee-mushroom-ganoderma-12-x-28-grams.jpg",
    "https://alibooster.com/62-home_default/dxn-white-coffee-soluble-zhino-coffee-mushroom-ganoderma-12-x-28-grams.jpg",
  ],
  "spirulina-tablets": [
    "https://i.ebayimg.com/images/g/2hEAAOSw5IFnBshI/s-l1200.jpg",
    "https://f.nooncdn.com/p/pnsku/N32454349A/45/_/1767607796/c9c5ac75-0962-4b2b-ba4f-9dfd7d51a2e7.jpg",
    "https://f.nooncdn.com/p/v1685615374/N32454349A_2.jpg",
    "https://f.nooncdn.com/p/v1578484301/N32454349A_3.jpg",
  ],
  "rg-reishi-gano": [
    "https://f.nooncdn.com/p/v1575375487/N32465792A_1.jpg",
    "https://f.nooncdn.com/p/v1596036801/N32465792A_2.jpg",
    "https://f.nooncdn.com/p/v1575380193/N32474440A_1.jpg",
    "https://img-cdn.heureka.group/v1/50846caa-b94d-5f77-99ca-35aabb3a9c3d.jpg",
  ],
  "gl-ganocelium": [
    "https://f.nooncdn.com/p/v1579351375/N32473839A_1.jpg",
    "https://f.nooncdn.com/p/v1579349899/N32473839A_2.jpg",
    "https://1.bp.blogspot.com/-y9X0Pywb484/YG3fPnrmLWI/AAAAAAAALPQ/TNtC1O2N6EU8QylHpwTTP2x2p1OxLRV_wCLcBGAsYHQ/s16000/Ganocelium-90.png",
    "https://i.ebayimg.com/images/g/5-0AAOSwtXJkUYGv/s-l1200.jpg",
  ],
  "cordyceps-coffee-3-in-1": [
    "https://beatusnatura.com/132-large_default/cordyceps-coffee-3-in-1.jpg",
    "https://beatusnatura.com/134-large_default/cordyceps-coffee-3-in-1.jpg",
    "https://beatusnatura.com/259-large_default/cordyceps-coffee-3-in-1.jpg",
  ],
  "cocozhi-cocoa-drink": [
    "https://beatusnatura.com/223-large_default/chokolate-drink-dxn.jpg",
    "https://beatusnatura.com/224-large_default/chokolate-drink-dxn.jpg",
    "https://beatusnatura.com/225-large_default/chokolate-drink-dxn.jpg",
  ],
  "spica-tea": [
    "https://alibooster.com/837-large_default/dxn-spica-tea-green-mushroom-tea-ganoderma-and-radix-glycyrrhizae-licorice-root.jpg",
    "https://alibooster.com/838-large_default/dxn-spica-tea-green-mushroom-tea-ganoderma-and-radix-glycyrrhizae-licorice-root.jpg",
    "https://alibooster.com/839-large_default/dxn-spica-tea-green-mushroom-tea-ganoderma-and-radix-glycyrrhizae-licorice-root.jpg",
  ],
  "morinzhi-fruit-drink": [
    "https://beatusnatura.com/384-large_default/morinzhi-285-ml-juice.jpg",
    "https://beatusnatura.com/385-large_default/morinzhi-285-ml-juice.jpg",
    "https://beatusnatura.com/374-large_default/dxn-morinzhi-700-ml.jpg",
    "https://beatusnatura.com/375-large_default/dxn-morinzhi-700-ml.jpg",
  ],
  "ganozhi-toothpaste": [
    "https://beatusnatura.com/405-large_default/toothpaste-ganozhi-dxn.jpg",
    "https://beatusnatura.com/406-large_default/toothpaste-ganozhi-dxn.jpg",
  ],
  "ganozhi-soap": [
    "https://beatusnatura.com/403-large_default/soap-dxn.jpg",
    "https://beatusnatura.com/404-large_default/soap-dxn.jpg",
  ],
  "ganozhi-shampoo": [
    "https://beatusnatura.com/401-large_default/ganozhi-shampoo-250-ml.jpg",
    "https://beatusnatura.com/402-large_default/ganozhi-shampoo-250-ml.jpg",
    "https://beatusnatura.com/505-large_default/ganozhi-shampoo-250-ml.jpg",
  ],
  "spirulina-cereal": [
    "https://beatusnatura.com/376-large_default/spirulina-cereal-dxn.jpg",
    "https://beatusnatura.com/377-large_default/spirulina-cereal-dxn.jpg",
    "https://beatusnatura.com/378-large_default/spirulina-cereal-dxn.jpg",
  ],
};

type Seed = Omit<Product, "id" | "shippingInfo" | "archived" | "approvedForAI" | "createdAt" | "updatedAt"> &
  Partial<Pick<Product, "approvedForAI" | "archived">>;

function product(seed: Seed, index: number): Product {
  return {
    id: `prd_${String(index + 1).padStart(3, "0")}`,
    shippingInfo: SHIPPING_INFO,
    archived: false,
    approvedForAI: true,
    createdAt: daysAgo(400 - index * 20),
    updatedAt: daysAgo(3 + index),
    images: IMAGES[seed.slug],
    ...seed,
  };
}

const seeds: Seed[] = [
  {
    slug: "lingzhi-black-coffee",
    name: "Lingzhi Black Coffee",
    category: "coffee",
    price: 620,
    unit: "Box of 30 sachets (4.5g each)",
    stockStatus: "in_stock",
    stockQuantity: 42,
    summary: "A simple 2-in-1 black coffee blended with Ganoderma extract. No creamer, no sugar.",
    description:
      "Lingzhi Black Coffee is a straightforward instant black coffee blended with Ganoderma (lingzhi mushroom) extract. It has a clean, slightly bold coffee profile, which makes it a favorite for customers who prefer their coffee without creamer or sugar, or who like to adjust sweetness themselves.",
    ingredients: ["Instant coffee", "Ganoderma extract"],
    preparation:
      "Empty one sachet into a cup. Add 120–150 ml of hot water and stir well. Adjust the amount of water to your preferred strength. Add sweetener or milk if you like.",
    productInfo: [
      { label: "Type", value: "2-in-1 instant black coffee" },
      { label: "Net content", value: "30 sachets × 4.5 g" },
      { label: "Sugar", value: "None added" },
      { label: "Storage", value: "Cool, dry place away from sunlight" },
      PACKAGING_REF,
    ],
    faqs: [
      { question: "Is this sweet?", answer: "No. There is no sugar or creamer added, so you can adjust it yourself." },
      { question: "How many cups per box?", answer: "One sachet makes one cup, so a box makes 30 cups." },
      { question: "What does it taste like?", answer: "A clean, slightly bold black coffee taste with a subtle earthy note." },
    ],
    importantInfo: FOOD_NOTICE,
    tags: ["black coffee", "no sugar", "2-in-1"],
    aliases: ["black coffee", "lingzhi black", "2 in 1", "2-in-1", "kape na black", "barako"],
    visual: "coffee",
    tone: "coffee",
    gallery: ["coffee", "cream", "clay"],
    isBestSeller: true,
    typicalReorderDays: 30,
  },
  {
    slug: "lingzhi-coffee-3-in-1",
    name: "Lingzhi Coffee 3-in-1",
    category: "coffee",
    price: 650,
    unit: "Box of 20 sachets (21g each)",
    stockStatus: "in_stock",
    stockQuantity: 58,
    summary: "Creamy and lightly sweet everyday coffee with creamer, sugar, and Ganoderma extract.",
    description:
      "Lingzhi Coffee 3-in-1 combines instant coffee, non-dairy creamer, and sugar with Ganoderma extract for a smooth, creamy cup. It's the most popular choice for customers who want a ready-to-drink coffee that tastes familiar and comforting.",
    ingredients: ["Non-dairy creamer", "Sugar", "Instant coffee", "Ganoderma extract"],
    preparation:
      "Empty one sachet into a cup. Add 150 ml of hot water and stir. For iced coffee, dissolve in 50 ml hot water first, then add ice and cold water.",
    productInfo: [
      { label: "Type", value: "3-in-1 instant coffee" },
      { label: "Net content", value: "20 sachets × 21 g" },
      { label: "Taste", value: "Creamy, lightly sweet" },
      { label: "Storage", value: "Cool, dry place away from sunlight" },
      PACKAGING_REF,
    ],
    faqs: [
      { question: "What's the difference from Lingzhi Black Coffee?", answer: "3-in-1 already includes creamer and sugar, so it tastes creamier and sweeter. Black Coffee has no creamer or sugar." },
      { question: "Can I make iced coffee with this?", answer: "Yes. Dissolve it in a little hot water first, then add ice and cold water." },
      { question: "Does it contain sugar?", answer: "Yes, sugar is one of the ingredients. Check the packaging for full nutrition information." },
    ],
    importantInfo: FOOD_NOTICE,
    tags: ["3-in-1", "creamy", "bestseller"],
    aliases: ["lingzhi coffee", "lingzhi 3 in 1", "lingzhi 3-in-1", "3 in 1", "3-in-1", "3in1", "lingzhi"],
    visual: "coffee",
    tone: "clay",
    gallery: ["clay", "cream", "coffee"],
    isBestSeller: true,
    typicalReorderDays: 40,
  },
  {
    slug: "white-coffee-zhino",
    name: "White Coffee Zhino",
    category: "coffee",
    price: 690,
    unit: "Box of 20 sachets (28g each)",
    stockStatus: "in_stock",
    stockQuantity: 35,
    summary: "Extra creamy white coffee with a mellow roast. Great for those who like milky coffee.",
    description:
      "White Coffee Zhino is a smooth, milky instant coffee with a mellow roast profile. It's designed for people who prefer a lighter, café-style white coffee over a strong black cup.",
    ingredients: ["Non-dairy creamer", "Sugar", "Instant white coffee", "Ganoderma extract"],
    preparation: "Empty one sachet into a cup. Add 150–180 ml of hot water and stir well.",
    productInfo: [
      { label: "Type", value: "Instant white coffee" },
      { label: "Net content", value: "20 sachets × 28 g" },
      { label: "Taste", value: "Milky, mellow" },
      { label: "Storage", value: "Cool, dry place away from sunlight" },
      PACKAGING_REF,
    ],
    faqs: [
      { question: "Is it sweeter than 3-in-1?", answer: "It is creamier and milder. Sweetness is similar, but the coffee taste is lighter." },
      { question: "How should I store opened sachets?", answer: "Use opened sachets right away. Keep unopened ones sealed in a cool, dry place." },
    ],
    importantInfo: FOOD_NOTICE,
    tags: ["white coffee", "creamy", "mild"],
    aliases: ["white coffee", "zhino", "white"],
    visual: "coffee",
    tone: "cream",
    gallery: ["cream", "clay", "coffee"],
    isBestSeller: true,
    typicalReorderDays: 35,
  },
  {
    slug: "cordyceps-coffee-3-in-1",
    name: "Cordyceps Coffee 3-in-1",
    category: "coffee",
    price: 720,
    unit: "Box of 20 sachets (21g each)",
    stockStatus: "low_stock",
    stockQuantity: 6,
    summary: "A 3-in-1 coffee blend with Cordyceps and Ganoderma extracts. Smooth and slightly sweet.",
    description:
      "Cordyceps Coffee 3-in-1 is a creamy instant coffee that includes Cordyceps and Ganoderma extracts. It has a smooth body and a gentle sweetness, similar to a classic 3-in-1.",
    ingredients: ["Non-dairy creamer", "Sugar", "Instant coffee", "Cordyceps extract", "Ganoderma extract"],
    preparation: "Empty one sachet into a cup. Add 150 ml of hot water and stir well.",
    productInfo: [
      { label: "Type", value: "3-in-1 instant coffee" },
      { label: "Net content", value: "20 sachets × 21 g" },
      { label: "Taste", value: "Smooth, lightly sweet" },
      PACKAGING_REF,
    ],
    faqs: [
      { question: "How is this different from Lingzhi Coffee 3-in-1?", answer: "Both are creamy 3-in-1 blends. This one also includes Cordyceps extract, and many customers describe it as slightly smoother." },
    ],
    importantInfo: FOOD_NOTICE,
    tags: ["3-in-1", "cordyceps"],
    aliases: ["cordyceps", "cordyceps coffee"],
    visual: "coffee",
    tone: "forest",
    gallery: ["forest", "cream", "coffee"],
    isBestSeller: false,
    typicalReorderDays: 40,
  },
  {
    slug: "cocozhi-cocoa-drink",
    name: "Cocozhi Cocoa Drink",
    category: "beverages",
    price: 680,
    unit: "Box of 20 sachets (20g each)",
    stockStatus: "in_stock",
    stockQuantity: 27,
    summary: "A rich instant cocoa drink with Ganoderma extract. Enjoy hot or cold, great for kids and adults.",
    description:
      "Cocozhi is an instant cocoa drink with a rich chocolate taste. It's a popular coffee-free option for the whole family and works well as a warm drink or a cold chocolate drink.",
    ingredients: ["Sugar", "Non-dairy creamer", "Cocoa powder", "Ganoderma extract"],
    preparation: "Mix one sachet with 150 ml of hot water. For a cold drink, dissolve in a little hot water, then add cold water and ice.",
    productInfo: [
      { label: "Type", value: "Instant cocoa drink" },
      { label: "Net content", value: "20 sachets × 20 g" },
      { label: "Caffeine", value: "Contains naturally occurring caffeine from cocoa" },
      PACKAGING_REF,
    ],
    faqs: [
      { question: "Is it okay for kids?", answer: "Many families serve it to children as a chocolate drink. Please check the ingredients for allergies and ask a pediatrician if you have concerns." },
      { question: "Does it contain coffee?", answer: "No, it's a cocoa drink with no coffee." },
    ],
    importantInfo: FOOD_NOTICE,
    tags: ["cocoa", "chocolate", "coffee-free"],
    aliases: ["cocozhi", "cocoa", "chocolate", "tsokolate", "choco"],
    visual: "powder",
    tone: "coffee",
    gallery: ["coffee", "clay", "cream"],
    isBestSeller: true,
    typicalReorderDays: 30,
  },
  {
    slug: "spica-tea",
    name: "Spica Tea",
    category: "beverages",
    price: 450,
    unit: "Box of 20 tea bags",
    stockStatus: "in_stock",
    stockQuantity: 19,
    summary: "A light herbal tea blend with a warm, spiced aroma. Caffeine-light and easy to enjoy.",
    description:
      "Spica Tea is a herbal tea blend with a warm, gently spiced aroma. It's a nice alternative for customers who want a light drink in the afternoon or evening.",
    ingredients: ["Herbal tea blend", "Spices", "Ganoderma extract"],
    preparation: "Steep one tea bag in 200 ml of hot water for 3–5 minutes. Add honey or lemon if desired.",
    productInfo: [
      { label: "Type", value: "Herbal tea bags" },
      { label: "Net content", value: "20 tea bags" },
      PACKAGING_REF,
    ],
    faqs: [{ question: "Can I drink it cold?", answer: "Yes. Brew it strong with hot water, let it cool, then pour over ice." }],
    importantInfo: FOOD_NOTICE,
    tags: ["tea", "herbal"],
    aliases: ["spica", "tea", "tsaa", "herbal tea"],
    visual: "tea",
    tone: "sage",
    gallery: ["sage", "cream", "leaf"],
    isBestSeller: false,
    typicalReorderDays: 30,
  },
  {
    slug: "morinzhi-fruit-drink",
    name: "Morinzhi Fruit Drink",
    category: "beverages",
    price: 1050,
    unit: "Bottle, 700 ml",
    stockStatus: "pre_order",
    stockQuantity: 0,
    summary: "A ready-to-drink noni fruit beverage. Available for pre-order; the seller will confirm the schedule.",
    description:
      "Morinzhi is a ready-to-drink fruit beverage made with noni (Morinda citrifolia) fruit juice. It has a tart, fruity taste and is usually enjoyed chilled in small servings.",
    ingredients: ["Noni fruit juice", "Grape juice", "Water"],
    preparation: "Shake well before use. Serve chilled. Refrigerate after opening and consume within the period stated on the label.",
    productInfo: [
      { label: "Type", value: "Ready-to-drink fruit beverage" },
      { label: "Net content", value: "700 ml" },
      { label: "Storage", value: "Refrigerate after opening" },
      PACKAGING_REF,
    ],
    faqs: [{ question: "When will it be available?", answer: "It's on pre-order. Send an inquiry and the seller will confirm the expected arrival date." }],
    importantInfo: FOOD_NOTICE,
    tags: ["fruit drink", "pre-order"],
    aliases: ["morinzhi", "noni", "noni juice"],
    visual: "bottle",
    tone: "leaf",
    gallery: ["leaf", "sage", "cream"],
    isBestSeller: false,
    typicalReorderDays: 30,
  },
  {
    slug: "spirulina-tablets",
    name: "Spirulina Tablets",
    category: "supplements",
    price: 780,
    unit: "Bottle of 120 tablets",
    stockStatus: "in_stock",
    stockQuantity: 31,
    summary: "Food supplement tablets made from spirulina algae. Not a replacement for medication.",
    description:
      "Spirulina Tablets are a food supplement made from spirulina, a blue-green algae. They come in an easy-to-carry bottle. Please follow the label directions and consult a healthcare professional if you have any medical condition.",
    ingredients: ["Spirulina (Arthrospira platensis)"],
    preparation: "Follow the serving directions printed on the label. Take with water. Do not exceed the recommended serving.",
    productInfo: [
      { label: "Type", value: "Food supplement (tablet)" },
      { label: "Net content", value: "120 tablets" },
      { label: "Storage", value: "Keep tightly closed in a cool, dry place" },
      PACKAGING_REF,
    ],
    faqs: [
      { question: "How many tablets should I take?", answer: "Please follow the directions on the product label. For personal health advice, consult a healthcare professional." },
      { question: "Can I take it with my maintenance medicine?", answer: "Please ask your doctor or pharmacist before combining any supplement with medication." },
    ],
    importantInfo: SUPPLEMENT_NOTICE,
    tags: ["spirulina", "tablets", "food supplement"],
    aliases: ["spirulina", "spirulina tablets", "spiru"],
    visual: "capsule",
    tone: "leaf",
    gallery: ["leaf", "sage", "cream"],
    isBestSeller: true,
    typicalReorderDays: 30,
  },
  {
    slug: "rg-reishi-gano",
    name: "RG (Reishi Gano) Capsules",
    category: "supplements",
    price: 1850,
    unit: "Bottle of 90 capsules",
    stockStatus: "in_stock",
    stockQuantity: 14,
    summary: "Food supplement capsules made from Ganoderma lucidum (reishi) powder. Not a medicine.",
    description:
      "RG (Reishi Gano) is a food supplement in capsule form made from Ganoderma lucidum mushroom. It's often paired by customers with GL in their daily routine. It is not a medicine and should not replace any prescribed treatment.",
    ingredients: ["Ganoderma lucidum powder", "Capsule shell"],
    preparation: "Follow the serving directions printed on the label. Take with water.",
    productInfo: [
      { label: "Type", value: "Food supplement (capsule)" },
      { label: "Net content", value: "90 capsules" },
      PACKAGING_REF,
    ],
    faqs: [
      { question: "What's the difference between RG and GL?", answer: "Both are Ganoderma-based food supplements. RG is made from the mushroom's fruiting body while GL is made from the mycelium. The seller can share the label details of each." },
      { question: "Can this treat an illness?", answer: "No. It's a food supplement, not a medicine. Please consult a qualified healthcare professional for any medical concern." },
    ],
    importantInfo: SUPPLEMENT_NOTICE,
    tags: ["ganoderma", "capsules", "food supplement"],
    aliases: ["rg", "reishi", "reishi gano", "ganoderma capsules"],
    visual: "capsule",
    tone: "clay",
    gallery: ["clay", "cream", "forest"],
    isBestSeller: false,
    typicalReorderDays: 30,
  },
  {
    slug: "gl-ganocelium",
    name: "GL (Ganocelium) Capsules",
    category: "supplements",
    price: 1650,
    unit: "Bottle of 90 capsules",
    stockStatus: "low_stock",
    stockQuantity: 4,
    summary: "Food supplement capsules made from Ganoderma mycelium. Not a medicine.",
    description:
      "GL (Ganocelium) is a food supplement in capsule form made from Ganoderma mycelium. Customers often ask about it together with RG. It is not intended to diagnose, treat, or cure any condition.",
    ingredients: ["Ganoderma mycelium powder", "Capsule shell"],
    preparation: "Follow the serving directions printed on the label. Take with water.",
    productInfo: [
      { label: "Type", value: "Food supplement (capsule)" },
      { label: "Net content", value: "90 capsules" },
      PACKAGING_REF,
    ],
    faqs: [{ question: "Can I take RG and GL together?", answer: "Many customers buy both, but please follow the label directions and consult a healthcare professional for personal advice." }],
    importantInfo: SUPPLEMENT_NOTICE,
    tags: ["ganoderma", "capsules", "food supplement"],
    aliases: ["gl", "ganocelium", "mycelium"],
    visual: "capsule",
    tone: "forest",
    gallery: ["forest", "sage", "cream"],
    isBestSeller: false,
    typicalReorderDays: 30,
  },
  {
    slug: "ganozhi-toothpaste",
    name: "Ganozhi Toothpaste",
    category: "personal-care",
    price: 320,
    unit: "Tube, 150 g",
    stockStatus: "in_stock",
    stockQuantity: 40,
    summary: "Everyday fluoride-free toothpaste with a fresh, mild mint taste.",
    description:
      "Ganozhi Toothpaste is an everyday toothpaste with a mild mint flavor and a smooth texture. It's a simple add-on for households who already order coffee and beverages.",
    ingredients: ["Calcium carbonate", "Sorbitol", "Water", "Mint flavor", "Ganoderma extract"],
    preparation: "Brush at least twice a day. For children under 6, use a pea-sized amount under adult supervision.",
    productInfo: [
      { label: "Type", value: "Toothpaste" },
      { label: "Net content", value: "150 g" },
      { label: "Flavor", value: "Mild mint" },
      PACKAGING_REF,
    ],
    faqs: [{ question: "Is it too minty for kids?", answer: "The mint is mild. Kids under 6 should use a small amount with adult supervision." }],
    importantInfo: "Do not swallow. Keep out of reach of children under 6.",
    tags: ["toothpaste", "oral care"],
    aliases: ["toothpaste", "ganozhi toothpaste", "toothpaste ganozhi"],
    visual: "jar",
    tone: "sage",
    gallery: ["sage", "cream", "leaf"],
    isBestSeller: false,
    typicalReorderDays: 45,
  },
  {
    slug: "ganozhi-soap",
    name: "Ganozhi Soap",
    category: "personal-care",
    price: 180,
    unit: "Bar, 80 g",
    stockStatus: "in_stock",
    stockQuantity: 75,
    summary: "Gentle cleansing bar with a light, clean scent. Suitable for daily use.",
    description:
      "Ganozhi Soap is a gentle cleansing bar for everyday bathing. It lathers well, rinses clean, and has a light scent. It's one of the easiest products to add to a regular order.",
    ingredients: ["Soap base", "Glycerin", "Ganoderma extract", "Fragrance"],
    preparation: "Lather with water, apply to wet skin, and rinse well. Store on a draining soap dish to make the bar last longer.",
    productInfo: [
      { label: "Type", value: "Bath soap" },
      { label: "Net content", value: "80 g" },
      PACKAGING_REF,
    ],
    faqs: [{ question: "Is it okay for sensitive skin?", answer: "Please do a patch test first and stop using it if irritation occurs." }],
    importantInfo: PERSONAL_CARE_NOTICE,
    tags: ["soap", "bath"],
    aliases: ["soap", "sabon", "ganozhi soap"],
    visual: "soap",
    tone: "cream",
    gallery: ["cream", "sage", "clay"],
    isBestSeller: true,
    typicalReorderDays: 30,
  },
  {
    slug: "ganozhi-shampoo",
    name: "Ganozhi Shampoo",
    category: "personal-care",
    price: 450,
    unit: "Bottle, 250 ml",
    stockStatus: "out_of_stock",
    stockQuantity: 0,
    summary: "Mild everyday shampoo with a fresh scent. Currently restocking.",
    description:
      "Ganozhi Shampoo is a mild everyday shampoo with a fresh, clean scent. It's currently being restocked. Send an inquiry and the seller will let you know once it's available.",
    ingredients: ["Water", "Mild surfactants", "Ganoderma extract", "Fragrance"],
    preparation: "Apply to wet hair, massage gently, and rinse thoroughly. Repeat if needed.",
    productInfo: [
      { label: "Type", value: "Shampoo" },
      { label: "Net content", value: "250 ml" },
      PACKAGING_REF,
    ],
    faqs: [{ question: "When will it be back?", answer: "The seller is restocking. Send an inquiry to get notified." }],
    importantInfo: PERSONAL_CARE_NOTICE,
    tags: ["shampoo", "hair care"],
    aliases: ["shampoo", "ganozhi shampoo"],
    visual: "bottle",
    tone: "cream",
    gallery: ["cream", "leaf", "sage"],
    isBestSeller: false,
    typicalReorderDays: 45,
  },
  {
    slug: "spirulina-cereal",
    name: "Spirulina Cereal",
    category: "wellness",
    price: 590,
    unit: "Pack of 20 sachets (30g each)",
    stockStatus: "in_stock",
    stockQuantity: 22,
    summary: "Instant cereal drink with oats and spirulina. A quick, filling breakfast option.",
    description:
      "Spirulina Cereal is an instant cereal drink made with oats, corn, and spirulina. Just add hot water for a quick, warm breakfast on busy mornings.",
    ingredients: ["Oats", "Corn flour", "Sugar", "Non-dairy creamer", "Spirulina"],
    preparation: "Mix one sachet with 150–180 ml of hot water. Stir well and let it sit for a minute.",
    productInfo: [
      { label: "Type", value: "Instant cereal drink" },
      { label: "Net content", value: "20 sachets × 30 g" },
      PACKAGING_REF,
    ],
    faqs: [{ question: "Is it sweet?", answer: "It's lightly sweet. You can add more water for a milder taste." }],
    importantInfo: FOOD_NOTICE,
    tags: ["cereal", "breakfast"],
    aliases: ["cereal", "spirulina cereal", "breakfast drink"],
    visual: "powder",
    tone: "leaf",
    gallery: ["leaf", "cream", "sage"],
    isBestSeller: false,
    typicalReorderDays: 30,
  },
];

export const products: Product[] = seeds.map(product);
